FROM innersource-artefacts-docker.optum.cloud/ingested/confluentinc/cp-server-connect:8.1.2
LABEL workstream="Continuous Streaming Service - KAFMRSC (Kafka multi-region stretched cluster)" \
      maintainer="Harish" \
      email="gcpgkekafka@gmail.com" \
      cmdb_appid="AL12345"

